language: go

sudo: false

go:
  - 1.12.x
  - 1.11.x
  - tip

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...
