language: go

sudo: false

go:
  - 1.11.x
  - tip

before_install:
  - go get golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...
